Update en-US.json
Validated with https://jsonlint.com/ to fix error:
Uncaught error in ./functions/getInternationalizations.js:
        SyntaxError: /home/container/i18n/en-US.json: Expected double-quoted property name in JSON at position 735
    at parse (<anonymous>)
    at Module._extensions..json (node:internal/modules/cjs/loader:1631:39)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1096:12)
    at Module.require (node:internal/modules/cjs/loader:1298:19)
    at require (node:internal/modules/helpers:182:18)
    at /home/container/functions/getInternationalizations.js:21:26
    at Array.forEach (<anonymous>)
    at module.exports (/home/container/functions/getInternationalizations.js:17:11)
    at Object.run (/home/container/slashCommands/admin/foo.js:71:21)